/*proyectos*/
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const SELECCIONAR_PROYECTO =  'SELECCIONAR_PROYECTO';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO'; 
export const MOSTRAR_FORMULARIO = 'MOSTRAR_FORMULARIO';
export const ERROR_PROYECTO = 'ERROR_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const DESCARTAR_PROYECTO = 'DESCARTAR_PROYECTO';
export const FORMULARIO_EDITAR = 'FORMULARIO_EDITAR'  
export const ERROR_EDITAR = 'ERROR_EDITAR';
export const ACTUALIZAR_PROYECTO = 'ACTUALIZAR_PROYECTO';
export const ELIMINAR_PROYECTOS = 'ELIMINAR_PROYECTOS';

/*alertas*/
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';


/*tareas*/
export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const OBTENER_TAREA = 'OBTENER_TAREA';
export const DESCARTAR_TAREA = 'DESCARTAR_TAREA' 
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const ERROR_TAREA = 'ERROR_TAREA';
export const EDITAR_TAREA = 'EDITAR_TAREA';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const ELIMINAR_TAREAS = 'ELIMINAR_TAREAS';
 

/*login*/
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const DESCARTAR_ERROR_LOGIN = 'DESCARTAR_ERROR_LOGIN';
export const ERROR_NUEVA = 'ERROR_NUEVA';
export const DESCARTAR_ERROR_NUEVA = 'DESCARTAR_ERROR_NUEVA';
export const CREAR_CUENTA = 'CREAR_CUENTA'; 
export const REINICIAR_CREADO = 'REINICIAR_CREADO';
export const INICIAR_SESION = 'INICIAR_SESION'
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO'; 
export const ERROR_AUTENTICAR = 'ERROR_AUTENTICAR';
export const CERRAR_SESION = 'CERRAR_SESION';